# Generated by Django 4.2.3 on 2023-07-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
